version: "3.9" # Specify the Docker Compose version

services:
  # PostgreSQL database service
  db:
    image: postgres:latest # Use the official PostgreSQL image
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password # Set an environment variable for the password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data volume

  pgadmin:
    image: dpage/pgadmin4 # Use the official pgAdmin4 image
    ports:
      - "5050:80" # Map container port 80 (pgAdmin) to host port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Optional: Set a default email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: password # Set the password for the pgAdmin user
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Optional: Persist pgAdmin data (configurations)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data: # Define the persistent data volume for PostgreSQL
  pgadmin_data: # Optional: Define a persistent data volume for pgAdmin (if needed)
